drop database cryptocurrency;
create database cryptocurrency;
use cryptocurrency;
show tables;

CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP not null,
    PUBLIC_KEY VARCHAR(2000) not null,
    PRIVATE_KEY VARCHAR(3000) not null
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYER_ID INT not null,
    RECEIVER_ID INT not null,
    AMOUNT DECIMAL(9, 4) NOT NULL,
    MINER_REWARD DECIMAL(19, 4) DEFAULT 0 not null,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP not null,
    PAYER_SIGNATURE VARCHAR(3500),

    CONSTRAINT FK_PAYER_ID FOREIGN KEY (PAYER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT FK_RECEIVER_ID FOREIGN KEY (RECEIVER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE BLOCK (
    BLOCK_HASH VARCHAR(300) PRIMARY KEY,
    BLOCK_NUMBER INT AUTO_INCREMENT UNIQUE not null,
    PREVIOUS_HASH VARCHAR(300) not null,
    NONCE INT NOT NULL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP not null,
    FOREIGN KEY (PREVIOUS_HASH) REFERENCES BLOCK(BLOCK_HASH)
);

CREATE TABLE BLOCK_TRANSACTION (
    BLOCK_ID VARCHAR(300),
    TRANSACTION_ID INT,
    
    PRIMARY KEY (BLOCK_ID, TRANSACTION_ID),
    
    FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK(BLOCK_HASH),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION(TRANSACTION_ID)
);

CREATE TABLE WALLET (
    USER_ID INT PRIMARY KEY,
    WALLET_VALUE DECIMAL(9, 4) NOT NULL DEFAULT 0,
    PASSWORD VARCHAR(300) not null,

    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);